# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util/sanity/shapes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18util/sanity/shapes.proto\x12\x10mmtk.util.sanity\"@\n\x0fShapesIteration\x12-\n\x06\x65pochs\x18\x01 \x03(\x0b\x32\x1d.mmtk.util.sanity.ShapesEpoch\"6\n\x0bShapesEpoch\x12\'\n\x06shapes\x18\x01 \x03(\x0b\x32\x17.mmtk.util.sanity.Shape\"\x84\x01\n\x05Shape\x12*\n\x04kind\x18\x01 \x01(\x0e\x32\x1c.mmtk.util.sanity.Shape.Kind\x12\x0e\n\x06object\x18\x02 \x01(\x04\x12\x0f\n\x07offsets\x18\x03 \x03(\x12\".\n\x04Kind\x12\x0c\n\x08ValArray\x10\x00\x12\x0c\n\x08ObjArray\x10\x01\x12\n\n\x06Scalar\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'util.sanity.shapes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SHAPESITERATION']._serialized_start=46
  _globals['_SHAPESITERATION']._serialized_end=110
  _globals['_SHAPESEPOCH']._serialized_start=112
  _globals['_SHAPESEPOCH']._serialized_end=166
  _globals['_SHAPE']._serialized_start=169
  _globals['_SHAPE']._serialized_end=301
  _globals['_SHAPE_KIND']._serialized_start=255
  _globals['_SHAPE_KIND']._serialized_end=301
# @@protoc_insertion_point(module_scope)
